CREATE DATABASE IF NOT EXISTS OLIST_DB;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.RAW;
USE SCHEMA OLIST_DB.RAW;

-- Wymiar Klientów
CREATE or REPLACE TABLE  DIM_CUSTOMERS (
    CUSTOMER_ID STRING PRIMARY KEY,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,
    CUSTOMER_ZIP_CODE_PREFIX STRING
);

-- Wymiar Produktów
CREATE or REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_CATEGORY_NAME_ENGLISH STRING,
    PRODUCT_WEIGHT_G FLOAT,
    PRODUCT_LENGTH_CM FLOAT,
    PRODUCT_HEIGHT_CM FLOAT,
    PRODUCT_WIDTH_CM FLOAT
);

-- Wymiar Czasu
CREATE or REPLACE TABLE  DIM_DATE (
    DATE_KEY DATE PRIMARY KEY,
    DAY_OF_WEEK INT,
    MONTH INT,
    YEAR INT,
    IS_HOLIDAY BOOLEAN
);

CREATE OR REPLACE TABLE DIM_SELLERS (
    SELLER_ID STRING PRIMARY KEY,
    SELLER_ZIP_CODE_PREFIX NUMBER,
    SELLER_CITY VARCHAR(100),
    SELLER_STATE VARCHAR(10)
);

-- Tabela Faktów (Ziarnistość: pozycja w zamówieniu)
CREATE or REPLACE TABLE  FACT_ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID VARCHAR(50),
    PRODUCT_ID STRING REFERENCES DIM_PRODUCTS(PRODUCT_ID),
    CUSTOMER_ID STRING REFERENCES DIM_CUSTOMERS(CUSTOMER_ID),
    SELLER_ID STRING REFERENCES DIM_SELLERS(SELLER_ID),
    PRICE FLOAT,
    FREIGHT_VALUE FLOAT,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ,
    REVIEW_SCORE FLOAT,
    DATE_KEY DATE REFERENCES DIM_DATE(DATE_KEY)
);