CREATE DATABASE IF NOT EXISTS OLIST_DB;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.RAW;
USE SCHEMA OLIST_DB.RAW;


CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY DATE PRIMARY KEY,
    DAY_OF_WEEK INT,
    DAY_NAME STRING,
    MONTH INT,
    MONTH_NAME STRING,
    QUARTER INT,
    YEAR INT,
    IS_HOLIDAY BOOLEAN 
);


CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID STRING PRIMARY KEY, 
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,
    CUSTOMER_ZIP_CODE_PREFIX STRING
);


CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_CATEGORY_NAME_ENGLISH STRING,
    PRODUCT_WEIGHT_G FLOAT
);


CREATE OR REPLACE TABLE DIM_SELLERS (
    SELLER_ID STRING PRIMARY KEY,
    SELLER_ZIP_CODE_PREFIX NUMBER,
    SELLER_CITY STRING,
    SELLER_STATE STRING
);


CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
    
    PRODUCT_ID STRING REFERENCES DIM_PRODUCTS(PRODUCT_ID),
    CUSTOMER_ID STRING REFERENCES DIM_CUSTOMERS(CUSTOMER_ID),
    SELLER_ID STRING REFERENCES DIM_SELLERS(SELLER_ID),
    PURCHASE_DATE_KEY DATE REFERENCES DIM_DATE(DATE_KEY),      
    ESTIMATED_DELIVERY_KEY DATE REFERENCES DIM_DATE(DATE_KEY), 
    ACTUAL_DELIVERY_KEY DATE REFERENCES DIM_DATE(DATE_KEY),    
    ORDER_ID STRING, 
    PRICE FLOAT,
    FREIGHT_VALUE FLOAT,             
    REVIEW_SCORE INT             
);